<?xml version="1.0" encoding="UTF-8"?>
<testsuite assertions="4" tests="1" failures="1" name="Ruby11" skipped="0" time="44.206433" errors="0">
  <testcase assertions="4" name="test_step2" time="44.205681">
    <failure type="Test::Unit::AssertionFailedError" message="The hey is displayed....">
The hey is displayed.
&lt;false&gt; is not true. (Test::Unit::AssertionFailedError)
getreferredJIBE_IE.rb:131:in `test_step2'    </failure>
  </testcase>
  <system-out>
the action is done
the action is done twice now
  </system-out>
  <system-err>
  </system-err>
</testsuite>
